apiVersion: v1 
kind: ConfigMap
metadata:
  name: time-config
  namespace: devops 
data:
  TIME_FREQ: "11"

--- 
apiVersion: v1
kind: Pod 
metadata:
  name: time-check
  namespace: devops 
spec:
  containers:
  - name: time-check
    image: busybox:latest
    command: ["sh", "-c", "while true; do date >> /opt/devops/time/time-check.log; sleep $TIME_FREQ;done"]
    volumeMounts:
      - name: log-volume
        mountPath: /opt/devops/time
    env:
    - name: TIME_FREQ
      valueFrom:
        configMapKeyRef:
          name: time-config
          key: TIME_FREQ
  volumes:
  - name: log-volume
    emptyDir: {}